FROM node:22-bookworm

RUN npm install -g npm@10.9.9

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN groupadd -r nextjs && useradd -r -g nextjs nextjs

RUN chown -R nextjs:nextjs /app

USER nextjs

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--webpack", "-H", "0.0.0.0"]